version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  open-pull-requests-limit: 20
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
